name: Docs

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint-docs:
    name: Lint Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: FuelLabs/github-actions/setups/node@master
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: true
        env:
          PNPM_HOME: ~/.local/share/pnpm
          pnpm-store-path: ~/.local/share/pnpm/store/v3
      - name: Debug Info
        run: |
          pwd
          ls -la
      - name: Lint Check
        working-directory: path/to/your/project  # Set the correct working directory
        run: |
          pnpm lint:check

  markdown-link-check:
    name: Check Links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: gaurav-nelson/github-action-markdown-link-check@1.0.12

  docs-hub-check:
    name: Docs Hub Checks
    uses: FuelLabs/github-actions/.github/workflows/mdbook-docs.yml@master
    with:
      docs-src-path: 'docs/src'
      spellcheck-config-path: 'docs/.spellcheck.yml'
