name: Update Nightly Versions

on:
    workflow_dispatch: 
    repository_dispatch:
      types: [update_versions]

env:
  GITHUB_TOKEN: ${{ secrets.MIGRATIONS_BOT }}

jobs:
  update-nightly-versions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.18.2'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install

    - name: List files for debugging
      run: ls -R src

    - name: Run Script
      run: |
        pnpm install
        pnpm docs:update --from-workflow
